export type TaskTemplate = {
  id: string;
  title: string;
  target_crop: string;
  estimated_time: string;
  tools_needed: string;
  description: string;
  memo: string;
  exp: number;
  difficulty: number;
  require_photo: boolean;
  badge_name: string;
  badge_icon: string;
  category: "根菜" | "果菜" | "葉菜" | "土作り";
  timing?: string;
  reference_links?: string;
  source?: string;
};

export const VEGETABLE_TASK_TEMPLATES: TaskTemplate[] = [
  // ─── 土作り・共通基盤管理 ───
  {
    id: "tpl_soil_prep_spring",
    title: "⛏️ 【春の基盤作り】堆肥・苦土石灰の深耕混和＆整地",
    target_crop: "共通",
    category: "土作り",
    timing: "3月上旬〜4月中旬（作付け2週間前）",
    estimated_time: "50分",
    tools_needed: "剣先スコップ, レーキ, 完熟牛ふん堆肥, 苦土石灰, メジャー",
    description:
      "【資材散布】1平方メートルあたり堆肥2kg（スコップ約4杯）と苦土石灰100g（大人の一握り約2回分）をムラなく均一に撒く\n【深耕反転】スコップの刃を垂直に根元（深さ25〜30cm）まで踏み込み、下層の土をすくい上げて表裏をひっくり返す（天地返し）\n【土塊粉砕】スコップの背やクワの刃先を使い、拳大以上の硬い土の塊をピンポン玉以下の大きさになるまで細かく砕く\n【平滑整地】レーキの平らな背側を土の表面に軽く当て、手前へ滑らせるように引きながら凸凹のない水平な作土面を作る",
    memo: "多摩の黒ボク土は下層が踏み固められやすい！スコップの刃が隠れる深さまでしっかり耕し、石灰と堆肥を深くまで混ぜ込むのが根張りの基礎だよ。",
    reference_links: "https://example.com/agri/soil-preparation",
    source: "東京都『野菜栽培技術指針（本畑準備）』",
    difficulty: 3,
    exp: 70,
    require_photo: true,
    badge_name: "大地を拓く者",
    badge_icon: "⛏️",
  },
  {
    id: "tpl_summer_solar",
    title: "☀️ 【夏の土壌浄化】残渣撤去＆米ぬか太陽熱土壌消毒",
    target_crop: "共通",
    category: "土作り",
    timing: "7月下旬〜8月中旬（梅雨明け後の猛暑期）",
    estimated_time: "50分",
    tools_needed: "万能平グワ, 米ぬか（またはフスマ）, 透明ビニールシート, スコップ, ジョウロ（ホース）",
    description:
      "【完全残渣撤去】夏野菜の根・茎・落ち葉を地中に残さないようスコップで掘り上げて畑の外へ完全に持ち出す\n【資材混和】1平方メートルあたり米ぬか1kgを散布し、クワで深さ15cm程度の作土と均一に混ぜ合わせる\n【徹底潅水】握った土の塊から指の隙間に水がじわりとにじみ出る状態になるまで、ホースやジョウロで土壌深部まで水を注ぎ込む\n【密閉被覆】透明シートを土壌表面に密着させて展張し、四方の縁を深さ10cmの溝に埋めて足で強く踏み固め、完全密閉する",
    memo: "8月の猛暑期に1ヶ月密閉することで地温が50℃以上に達し、土の中のセンチュウや病原菌、雑草の種が一網打尽になるよ！",
    reference_links: "https://example.com/agri/solar-disinfection",
    source: "農林水産省『有機農業の栽培技術マニュアル（土壌消毒）』",
    difficulty: 3,
    exp: 75,
    require_photo: true,
    badge_name: "太陽の浄化師",
    badge_icon: "☀️",
  },

  // ─── 果菜類：ミニトマト ───
  {
    id: "tpl_tomato_start",
    title: "🍅 【初回必須】ミニトマトの若苗定植＆仮支柱・水やりガード",
    target_crop: "ミニトマト",
    category: "果菜",
    timing: "5月上旬（GW前後・晩霜の心配がなくなってから）",
    estimated_time: "40分",
    tools_needed: "苗, 移植ゴテ, ジョウロ（水5L）, 細支柱（90cm）, 麻紐, メジャー",
    description:
      "【植え穴掘削】株間50cmを測り、移植ゴテで苗ポットの土と同じ深さの穴を掘り、植え穴に500mlの水を注いで引くのを待つ\n【根鉢据付】人差し指と中指で苗の茎の根元を挟んでポットを逆さにし、根鉢を崩さずに引き抜いて穴に入れ、第一花房（黄色い花）を通路側に向ける\n【覆土鎮圧】株元へ周囲の土を寄せ、根鉢の上面が地面と水平になる深さで手のひらで軽く1回押さえて密着させる\n【仮支柱結束】苗の根元から5cm離れた位置に支柱を斜めに刺し、麻紐で茎側はゆったり、支柱側で固結びにする「8の字結び」で留める",
    memo: "トマトは花が咲いた方向に必ず実がつく！黄色い花を通路側に向けて植え付けると、後々の収穫作業が劇的に楽になるぞ。",
    reference_links: "https://example.com/agri/tomato-planting",
    source: "東京都『野菜栽培技術指針（トマト）』",
    difficulty: 2,
    exp: 50,
    require_photo: true,
    badge_name: "トマトルーキー",
    badge_icon: "🌱",
  },
  {
    id: "tpl_tomato_pruning",
    title: "✂️ 【樹形管理】ミニトマトのわき芽かき＆主枝1本誘引",
    target_crop: "ミニトマト",
    category: "果菜",
    timing: "5月下旬〜6月下旬（週1回来園ルーティン）",
    estimated_time: "20分",
    tools_needed: "園芸ハサミ（消毒済）, 麻紐, 太支柱（210cm）",
    description:
      "【わき芽判別】主茎と葉の付け根の間から斜め45度で上に向かって勢いよく伸びてくる「わき芽」を目視で確認する\n【指先摘除】わき芽の長さが3〜5cmの柔らかいうちに、指で根元を横に倒してポキッと折り取る（晴天の午前中に実施）\n【主枝誘引】伸びた主枝を太支柱に沿わせ、麻紐を茎に回してから支柱側で固結びし、指1本分の隙間を空けて遊びを作る\n【残渣回収】折ったわき芽は病害の感染源になるため、マルチの上や畝間に放置せずビニール袋に集めて処分する",
    memo: "わき芽を放置するとジャングル化して実が小さくなる！晴れた日の午前中に手で摘むと、傷口が夕方までに乾いて病気を防げるよ。",
    reference_links: "https://example.com/agri/tomato-pruning",
    source: "東京都『野菜栽培技術指針（トマト整枝法）』",
    difficulty: 2,
    exp: 35,
    require_photo: false,
    badge_name: "わき芽ハンター",
    badge_icon: "✂️",
  },
  {
    id: "tpl_tomato_care",
    title: "🧪 【肥培・通気】第1回追肥＆下葉かき",
    target_crop: "ミニトマト",
    category: "果菜",
    timing: "6月中旬（第1段果実がピンポン玉サイズに肥大した頃）",
    estimated_time: "25分",
    tools_needed: "化成肥料（8-8-8等）, 移植ゴテ, 園芸ハサミ",
    description:
      "【追肥散布】株元から20cm離れたマルチの縁にコテを差し込み、化成肥料15g（大さじ1杯）を入れて周囲の土と軽く混ぜる\n【下葉切除】地面に触れている最下段の葉や、黄色く変色した古い下葉の付け根を園芸ハサミで切り落とす\n【株元空間確保】第一花房のすぐ下にある主葉より下の空間をすっきりと開け、風通しの良いトンネル状態を作る\n【マルチ穴戻し】追肥したマルチの切れ目を土で軽く押さえ、肥料の揮散と地温上昇を防ぐ",
    memo: "最初の実が太る前に追肥をすると「木ボケ」して葉ばかり茂ってしまう。実がしっかり太ったのを確認してから追肥するのが鉄則だ！",
    reference_links: "https://example.com/agri/tomato-fertilizing",
    source: "東京都『野菜栽培技術指針（追肥管理）』",
    difficulty: 2,
    exp: 40,
    require_photo: true,
    badge_name: "肥培のバランサー",
    badge_icon: "⚖️",
  },
  {
    id: "tpl_tomato_harvest",
    title: "🧺 【完熟収穫】ミニトマトの朝採り＆先端摘心",
    target_crop: "ミニトマト",
    category: "果菜",
    timing: "7月上旬〜8月下旬",
    estimated_time: "30分",
    tools_needed: "収穫ハサミ, 収穫カゴ",
    description:
      "・ヘタの際まで真っ赤に色づいた果実のヘタの関節部分を親指で押し上げ、ハサミを使わずに手でポロッと収穫する\n・主枝の先端が支柱の頭部（第5〜6花房の上）に達したら、最上段の花房の上に葉を2枚残して先端をハサミで切り落とす（摘心）\n・収穫を終えた花房の下にある葉は、光合成の役目を終えているため順次ハサミで切り落とす\n・実割れを防ぐため、雨が降る前日または直後に赤くなっている実を優先して収穫する",
    memo: "最上段の上に葉を2枚残すのがプロの技！この葉が日よけになり、最上段の実までしっかり甘く完熟させてくれるぞ。",
    reference_links: "https://example.com/agri/tomato-harvest",
    source: "東京都『野菜栽培技術指針（トマト）』",
    difficulty: 1,
    exp: 40,
    require_photo: false,
    badge_name: "トマトマスター",
    badge_icon: "🧺",
  },

  // ─── 果菜類：ナス ───
  {
    id: "tpl_eggplant_start",
    title: "🍆 【初回必須】ナスの若苗定植＆あんどん（風よけ）設置",
    target_crop: "ナス",
    category: "果菜",
    timing: "5月上旬",
    estimated_time: "45分",
    tools_needed: "苗, 移植ゴテ, 肥料空き袋（またはポリ袋）, 短支柱（90cm）4本, ガムテープ, ジョウロ",
    description:
      "【定植穴準備】株間60cmを確保して深さ12cmの穴を掘り、水500mlを注ぎ込んで土にしっかり染み込ませる\n【定植】根鉢を崩さず苗を穴に入れ、土を被せて地表と高さを合わせ、根元を手のひらで軽く押さえて密着させる\n【あんどん骨組み】株の四方15cm離れた位置に90cm支柱を4本、深さ20cmまで垂直に打ち込んで長方形の枠を作る\n【袋被覆固定】底を切り抜いた肥料袋を筒状にして骨組みの上から被せ、支柱にガムテープで留めて風よけの囲いを完成させる",
    memo: "多摩の春は強風が吹き荒れる！ナスの大きな葉は風で擦れると生育が止まるから、定植当日にあんどんで囲うことが活着の命運を分けるよ。",
    reference_links: "https://example.com/agri/eggplant-start",
    source: "東京都『野菜栽培技術指針（ナス）』",
    difficulty: 2,
    exp: 55,
    require_photo: true,
    badge_name: "ナスの風防騎士",
    badge_icon: "🛡️",
  },
  {
    id: "tpl_eggplant_training",
    title: "🌿 【骨格形成】ナスの3本仕立て＆支柱交差結束",
    target_crop: "ナス",
    category: "果菜",
    timing: "6月上旬",
    estimated_time: "40分",
    tools_needed: "園芸支柱（180cm）3本, 麻紐, 剪定バサミ",
    description:
      "【主枝・側枝選定】一番花（最初に咲いた花）のすぐ真下から勢いよく伸びる元気なわき芽を2本選抜する\n【不要芽切除】主枝1本＋強い側枝2本の合計3本を残し、それより下の地面近くから出ている細かい芽をすべてハサミで切り落とす\n【交差支柱打込み】残した3本の枝の伸びる方向に合わせて支柱を3本、地面に深く斜めに刺し、中央で交差させて紐で固定する\n【誘引結束】それぞれの枝を対応する支柱へ麻紐で優しく誘導し、8の字結びで固定して風による揺れを止める",
    memo: "「一番花の下の2本」が最も力強く伸びる！主枝と合わせて3本立ちにすると、秋までバランス良く実がつき続けるぞ。",
    reference_links: "https://example.com/agri/eggplant-pruning",
    source: "東京都『野菜栽培技術指針（ナス整枝法）』",
    difficulty: 3,
    exp: 60,
    require_photo: true,
    badge_name: "三叉の仕立て師",
    badge_icon: "🔱",
  },
  {
    id: "tpl_eggplant_renew",
    title: "✂️ 【真夏の若返り】ナスの更新剪定＆根切り追肥",
    target_crop: "ナス",
    category: "果菜",
    timing: "7月下旬〜8月上旬",
    estimated_time: "45分",
    tools_needed: "剪定バサミ, 剣先スコップ, 化成肥料30g, ジョウロ（バケツ1杯の水）",
    description:
      "【枝の切り戻し】伸びすぎたすべての枝を、長さの半分から3分の1まで大胆にハサミで切り落とす\n【葉の残存確認】切り戻した各枝の先端付近に、光合成を維持するための青い葉が必ず1〜2枚残っている状態にする\n【根切り】株元から30cm離れた畝の肩口にスコップを垂直に踏み込み、古い根をザクザクと全周にわたって断ち切る\n【追肥・潅水】スコップを入れた溝に化成肥料30gを撒き、上から土を戻してバケツ1杯の水をたっぷりと注ぎ込む",
    memo: "盛夏に疲れた株を一度丸刈りに！古い根を切って新しい根を出させると、8月下旬からツヤツヤの絶品「秋ナス」が実るよ。",
    reference_links: "https://example.com/agri/eggplant-renewal",
    source: "東京都『野菜栽培技術指針（ナス更新剪定）』",
    difficulty: 4,
    exp: 85,
    require_photo: true,
    badge_name: "再生の切り戻し職人",
    badge_icon: "🔄",
  },

  // ─── 果菜類：キュウリ ───
  {
    id: "tpl_cucumber_start",
    title: "🥒 【初回必須】キュウリ浅植え＆合掌ネット展張",
    target_crop: "キュウリ",
    category: "果菜",
    timing: "5月上旬",
    estimated_time: "50分",
    tools_needed: "苗, 支柱（210cm）4本, 横通し用支柱1本, キュウリネット（10cm目）, パッカー, 麻紐, 移植ゴテ",
    description:
      "【浅植え定植】株間45cmで穴を掘り、根鉢の上面が周囲の地面より1cmほど高くなるよう「浅植え」にして土を寄せ軽く押さえる\n【合掌フレーム構築】畝をまたぐように2本ずつの支柱を斜めに交差させて地面に刺し、頭部に横通し支柱を渡して麻紐で結束する\n【ネット展張】合掌の骨組み全体にキュウリネットを被せ、たるみが出ないよう四隅をピンと引っ張りながらパッカーで固定する\n【初期誘引・潅水】苗の茎をネットの最下段に麻紐で8の字に留め、株元周辺に500mlの水を静かに注ぐ",
    memo: "キュウリの根は呼吸量が多いので深く埋めると窒息する！根鉢の頭が少し見えるくらいの浅植えが、立ち枯れ病を防ぐ最大のコツだ。",
    reference_links: "https://example.com/agri/cucumber-start",
    source: "東京都『野菜栽培技術指針（キュウリ）』",
    difficulty: 3,
    exp: 60,
    require_photo: true,
    badge_name: "グリーンネットビルダー",
    badge_icon: "🕸️",
  },
  {
    id: "tpl_cucumber_care",
    title: "✂️ 【増収仕立て】下段5節のわき芽・雌花摘除＆つる上げ",
    target_crop: "キュウリ",
    category: "果菜",
    timing: "5月下旬〜6月中旬",
    estimated_time: "25分",
    tools_needed: "園芸ハサミ, 麻紐",
    description:
      "【節数カウント】地面に近い葉の付け根から上に向かって節の数を1、2、3、4、5と順番に数える\n【下段完全摘除】第1節から第5節までについている小さなわき芽と、キュウリの赤ちゃんの雌花をすべて手で摘み取る\n【中段子づる摘心】第6節より上から伸びる子づる（側枝）は、葉を1〜2枚残した位置で先端をハサミで切り止める\n【主づるネット誘引】親づる（主茎）の先端をネットの網目にジグザグに通し、麻紐でネットに軽く結びつけて上へ導く",
    memo: "最初の5個の実をもったいないと思わずに摘み取ることで、株全体にパワーがついて、夏までに数十本以上の収穫につながるぞ！",
    reference_links: "https://example.com/agri/cucumber-pruning",
    source: "東京都『野菜栽培技術指針（キュウリ整枝）』",
    difficulty: 2,
    exp: 45,
    require_photo: true,
    badge_name: "つる上げナビゲーター",
    badge_icon: "📈",
  },

  // ─── 果菜類：ピーマン ───
  {
    id: "tpl_pepper_start",
    title: "🫑 【初回必須】ピーマンの定植＆4本仕立て用仮留め",
    target_crop: "ピーマン",
    category: "果菜",
    timing: "5月上旬〜中旬",
    estimated_time: "35分",
    tools_needed: "苗, 移植ゴテ, ジョウロ, 支柱（150cm）4本, 麻紐",
    description:
      "【植え穴潅水】株間50cmで深さ10cmの穴を掘り、水をたっぷり注いで完全に引くまで待つ\n【定植】一番花のつぼみが確認できる苗を、根鉢を崩さずに据え置き、周りの土を寄せて株元を手のひらで鎮圧する\n【4方向支柱打ち】株の中心から20cm離れた東西南北の4箇所に、外側にやや広がる角度で支柱を深く打ち込む\n【仮結束】風で主茎が折れないよう、中央の主枝を支柱の1本に麻紐でゆったりと結びつける",
    memo: "ピーマンの枝は木質化が遅くてガラスのように折れやすい！突風でポキッと逝かないよう、定植したらすぐに支柱で揺れを抑えよう。",
    reference_links: "https://example.com/agri/pepper-start",
    source: "東京都『野菜栽培技術指針（ピーマン）』",
    difficulty: 2,
    exp: 50,
    require_photo: true,
    badge_name: "グリーンフォース",
    badge_icon: "🫑",
  },

  // ─── 果菜類：エダマメ ───
  {
    id: "tpl_edamame_start",
    title: "🫛 【初回必須】エダマメの点まき＆鳥よけ不織布ベタがけ",
    target_crop: "エダマメ",
    category: "果菜",
    timing: "5月中旬〜下旬",
    estimated_time: "30分",
    tools_needed: "種子, 移植ゴテ（または指）, 不織布, U字ピン, ジョウロ",
    description:
      "【播種穴あけ】株間30cm・条間30cmを測り、指の第一関節（深さ2cm）を押し込んで三角形を描くように3箇所穴を開ける\n【点まき覆土】各穴に種を1粒ずつ（計3粒）横向きに落とし、土を被せて手のひらで体重をかけてしっかり上から押さえる\n【不織布ベタがけ】発芽時の鳥害（ハト・カラス）を防ぐため、畝の表面全体に不織布をふんわりと直接被せる\n【全周ピン留め・潅水】風でめくれないよう縁を1m間隔でU字ピンで地面に留め、不織布の上からジョウロでたっぷり水を撒く",
    memo: "カラスやハトは土の中の豆を狙っているぞ！芽が出て最初の本葉が開くまでは、ネットの隙間をゼロにして守り抜こう。",
    reference_links: "https://example.com/agri/edamame-sowing",
    source: "東京都『野菜栽培技術指針（エダマメ）』",
    difficulty: 1,
    exp: 40,
    require_photo: true,
    badge_name: "豆まきマスター",
    badge_icon: "🫛",
  },
  {
    id: "tpl_edamame_care",
    title: "✂️ 【選抜・増収】エダマメの間引き2本立ち＆株元土寄せ",
    target_crop: "エダマメ",
    category: "果菜",
    timing: "6月上旬（初生葉が開いた頃）",
    estimated_time: "25分",
    tools_needed: "園芸ハサミ, 移植ゴテ",
    description:
      "【間引き選抜】1箇所から発芽した3本のうち、生育が最も遅れているものや茎が細い1本を目視で選ぶ\n【根元ハサミ切り】残す2本の根を傷つけないよう、間引く株を引き抜かずに地際ギリギリでハサミで切り落とす\n【中耕土寄せ】株の周囲5cm離れた土を移植ゴテで軽くほぐし、双葉（初生葉）が半分隠れる高さまで株元に土を寄せる\n【鎮圧】寄せた土を手で軽くキュッと押さえ、苗がグラグラと風で倒れないよう根元を安定させる",
    memo: "エダマメは「1箇所2本立ち」で育てるのが極意！お互いに寄り添って風に耐え、実のつき具合も格段にアップするんだ。",
    reference_links: "https://example.com/agri/edamame-care",
    source: "東京都『野菜栽培技術指針（エダマメ管理）』",
    difficulty: 2,
    exp: 35,
    require_photo: false,
    badge_name: "ツインズキーパー",
    badge_icon: "👯",
  },

  // ─── 果菜類：オクラ ───
  {
    id: "tpl_okra_start",
    title: "⭐ 【初回必須】オクラの4粒点まき＆初期保温被覆",
    target_crop: "オクラ",
    category: "果菜",
    timing: "5月中旬（地温が20℃を超えてから）",
    estimated_time: "30分",
    tools_needed: "種子, ぬるま湯（浸種用）, 不織布, ジョウロ",
    description:
      "【種の前処理】硬い殻の吸水を促すため、播種前日の晩から種を一晩ぬるま湯に浸しておく\n【播種穴あけ】株間35cmで深さ1.5cmの穴を指で4箇所開け、1穴に1粒ずつ種を配置する\n【覆土鎮圧】土を1.5cm被せた後、手のひらで土を強く押し固めて種と土を密着させる\n【保温被覆・潅水】寒さに弱いため畝に不織布をベタがけし、上から水が染み込むまで十分に散水する",
    memo: "アフリカ原産のオクラは超寒がり！地温が足りないと土の中で腐ってしまうから、しっかり暖かくなった5月中旬にまくのが鉄則だよ。",
    reference_links: "https://example.com/agri/okra-start",
    source: "東京都『野菜栽培技術指針（オクラ）』",
    difficulty: 1,
    exp: 40,
    require_photo: true,
    badge_name: "スターシード",
    badge_icon: "⭐",
  },
  {
    id: "tpl_okra_harvest",
    title: "🗡️ 【連続増収】オクラの若採り収穫＆直下葉かき",
    target_crop: "オクラ",
    category: "果菜",
    timing: "7月上旬〜9月下旬",
    estimated_time: "25分",
    tools_needed: "収穫ハサミ, 軍手, 収穫袋",
    description:
      "・開花後4〜5日、長さ7〜8cm前後の角が立ちすぎていない柔らかい実をハサミで切り取る\n・収穫した実のすぐ下についている大きな側葉を、ハサミで主茎の際から切り落とす\n・実より上に展開している元気な葉だけを残し、下部に日光と風が通るすっきりした樹形を保つ\n・細かなトゲで皮膚がかゆくなるのを防ぐため、必ず手袋と長袖を着用して作業する",
    memo: "「1個採ったらその下の葉を1枚落とす」のがオクラの合言葉！下の葉を取り除くことで風通しが良くなり、次の実へと栄養が集中するぞ。",
    reference_links: "https://example.com/agri/okra-harvest",
    source: "農林水産省『有機農業の栽培技術マニュアル（オクラ管理）』",
    difficulty: 2,
    exp: 40,
    require_photo: false,
    badge_name: "グリーンセーバー",
    badge_icon: "🗡️",
  },

  // ─── 果菜類：トウモロコシ ───
  {
    id: "tpl_corn_start",
    title: "🌽 【初回必須】トウモロコシの2条千鳥まき＆初期保温",
    target_crop: "トウモロコシ",
    category: "果菜",
    timing: "4月下旬〜5月上旬",
    estimated_time: "40分",
    tools_needed: "種子, 穴あきマルチ（または移植ゴテ）, 不織布トンネル資材, ジョウロ",
    description:
      "【2条千鳥配置】受粉効率を高めるため、条間50cm・株間30cmでジグザグ（千鳥状）に配置を決める\n【播種覆土】1箇所に深さ2cmの穴を指で開け、種を尖った方を下にして3粒置き、土を被せて手で強く押さえる\n【トンネル被覆】ダンポール支柱をアーチ状に刺し、上から不織布を被せてパッカーで固定する\n【初期潅水】トンネルの裾に隙間がないことを確認し、ジョウロで畝全体にたっぷり水を撒く",
    memo: "1列で長く植えると花粉が風で飛んでいって受粉しない！「2列で四角いエリアを作るように」千鳥で植えるのが、実詰まりを良くする秘訣だ。",
    reference_links: "https://example.com/agri/corn-start",
    source: "東京都『野菜栽培技術指針（トウモロコシ）』",
    difficulty: 2,
    exp: 50,
    require_photo: true,
    badge_name: "コーンフロンティア",
    badge_icon: "🌽",
  },
  {
    id: "tpl_corn_pollinate",
    title: "🌾 【実詰まり向上】トウモロコシの人工授粉＆ヤングコーン除房",
    target_crop: "トウモロコシ",
    category: "果菜",
    timing: "6月中旬〜下旬（雄穂開花時）",
    estimated_time: "30分",
    tools_needed: "園芸ハサミ, 収穫袋",
    description:
      "・茎のてっぺんに咲いた雄穂をハサミで1本切り取り、花粉が出ていることを確認する\n・下の方の雌穂から出ている絹糸（ヒゲ）全体に、切り取った雄穂を直接トントンと擦りつけて花粉をつける\n・1株に複数着生した雌穂のうち、一番上の太い1房だけを残し、下段の第2・第3房を手で下向きにもぎ取る\n・もぎ取った下段の小さな房は、新鮮なヤングコーンとして持ち帰って加熱調理する",
    memo: "ヒゲの1本1本がコーンの粒につながっているんだ。花粉を均一につけてあげると、先端までびっしり詰まった極上コーンになるよ！",
    reference_links: "https://example.com/agri/corn-pollination",
    source: "東京都『野菜栽培技術指針（トウモロコシ管理）』",
    difficulty: 2,
    exp: 50,
    require_photo: true,
    badge_name: "ゴールドポリネーター",
    badge_icon: "🌽",
  },

  // ─── 果菜類：ズッキーニ ───
  {
    id: "tpl_zucchini_start",
    title: "🌼 【初回必須】ズッキーニの高畝定植＆仮支柱留め",
    target_crop: "ズッキーニ",
    category: "果菜",
    timing: "4月下旬〜5月上旬",
    estimated_time: "35分",
    tools_needed: "苗, 移植ゴテ, 支柱（120cm）, 麻紐, ジョウロ",
    description:
      "【幅広畝準備】株が巨大化するため株間70cm・条間80cmの広いスペースを確保し、中央に植え穴を掘る\n【根鉢定植】植え穴に500mlの水を注ぎ、引いた後に根鉢を崩さずに苗を据え置き、周りの土を寄せて軽く押さえる\n【支柱設置】風にあおられて主茎が折れるのを防ぐため、株元から5cm離れた位置に支柱を垂直に打ち込む\n【茎の結束】麻紐を使い、生長点を傷つけないよう茎の太い部分を支柱に8の字結びで固定する",
    memo: "ズッキーニはカボチャの仲間だけどつるが伸びず、大きな葉を広げて風で倒れやすい。植えた当日に必ず支柱で固定してあげよう。",
    reference_links: "https://example.com/agri/zucchini-start",
    source: "東京都『野菜栽培技術指針（ズッキーニ）』",
    difficulty: 2,
    exp: 45,
    require_photo: true,
    badge_name: "ズッキーニパイオニア",
    badge_icon: "🌼",
  },
  {
    id: "tpl_zucchini_pollinate",
    title: "🐝 【朝限定】ズッキーニの早朝人工授粉＆適期収穫",
    target_crop: "ズッキーニ",
    category: "果菜",
    timing: "6月上旬〜7月下旬（朝9時前限定）",
    estimated_time: "20分",
    tools_needed: "小型ハサミ",
    description:
      "・朝9時前までに畑へ行き、根元に実がない「雄花」と、根元がふくらんでいる「雌花」を見分ける\n・咲いている雄花をハサミで摘み取り、黄色い花弁（花びら）をちぎり取って中心の雄しべを露出させる\n・露出させた雄しべの先端を、雌花の中心にある雌しべ（柱頭）に優しくトントンと擦りつけて花粉をつける\n・開花後4〜5日経って長さ20cm前後になったみずみずしい実を、ハサミで切り取って収穫する",
    memo: "ズッキーニの花粉は暑さに極めて弱い！午前9時を過ぎると花粉の受精能力が落ちるから、朝露が残る早朝の受粉が成功の絶対条件だ。",
    reference_links: "https://example.com/agri/zucchini-pollination",
    source: "東京都『野菜栽培技術指針（ズッキーニ受粉）』",
    difficulty: 2,
    exp: 45,
    require_photo: true,
    badge_name: "モーニングビー",
    badge_icon: "🐝",
  },

  // ─── 根菜類：ジャガイモ ───
  {
    id: "tpl_potato_start",
    title: "🥔 【初回必須】ジャガイモの種芋カット＆溝植え元肥配置",
    target_crop: "ジャガイモ",
    category: "根菜",
    timing: "3月上旬〜中旬",
    estimated_time: "45分",
    tools_needed: "種芋, 包丁, 草木灰（または日陰乾燥）, クワ, 化成肥料, メジャー",
    description:
      "【種芋分割】60g以上の大きな種芋を、芽の数が均等になるよう包丁で縦に2分割し、切り口に草木灰を薄くまぶす\n【植え溝掘り】クワを使って幅20cm・深さ10cmのまっすぐな溝を掘る\n【配置と施肥】株間30cm間隔で切り口を下にして芋を置き、芋と芋のちょうど中間地点に化成肥料20gを置く\n【覆土鎮圧】掘り上げた土を溝へ戻して厚さ5cm程度覆土し、クワの背で軽く叩いて表面を平らに均す",
    memo: "肥料が直接種芋に触れると腐敗するぞ！必ず「芋と芋の間」に肥料を置くこと。多摩の春風で乾きやすいから覆土後は軽く叩いて密着させよう。",
    reference_links: "https://example.com/agri/potato-start",
    source: "東京都『野菜栽培技術指針（バレイショ）』",
    difficulty: 2,
    exp: 50,
    require_photo: true,
    badge_name: "ポテトプランター",
    badge_icon: "🥔",
  },
  {
    id: "tpl_potato_care",
    title: "⛏️ 【大粒化】ジャガイモの芽かき＆第1回追肥土寄せ",
    target_crop: "ジャガイモ",
    category: "根菜",
    timing: "4月中旬〜下旬（草丈が10〜15cmに達した頃）",
    estimated_time: "35分",
    tools_needed: "クワ（または三角ホー）, 化成肥料",
    description:
      "【残す茎の選別】株元から茂っている芽のうち、太くて青々とした元気な茎を1〜2本だけ選定する\n【芽かき実行】残す茎の根元を片手でしっかり地面に押さえ、不要な細い芽を斜め上方向に引き抜く\n【条間追肥】株と株の間の通路に、1平方メートルあたり化成肥料20gを均一にまく\n【土寄せ成形】クワを使って両側の土を株元へかき上げ、高さ5〜7cmの台形になるよう土を盛る",
    memo: "欲張って芽をたくさん残すと小粒の芋ばかりになる！残す芽の根元を押さえずに引くと、種芋ごと抜けてしまうから注意して抜こう。",
    reference_links: "https://example.com/agri/potato-care",
    source: "東京都『野菜栽培技術指針（バレイショ管理）』",
    difficulty: 3,
    exp: 55,
    require_photo: true,
    badge_name: "芽かきの達人",
    badge_icon: "👑",
  },
  {
    id: "tpl_potato_harvest",
    title: "🥔 【歓喜の収穫】ジャガイモの掘り上げ＆風乾",
    target_crop: "ジャガイモ",
    category: "根菜",
    timing: "6月上旬〜下旬（地上部が黄色く枯れた晴天日）",
    estimated_time: "50分",
    tools_needed: "万能フォーク（またはスコップ）, 収穫カゴ, 軍手",
    description:
      "・晴天が2〜3日続いて畑の土がサラサラに乾いている日を作業日として選ぶ\n・株元から30cm離れた場所にフォークを垂直に深く刺し、テコの原理で土を大きく持ち上げる\n・土の中から現れたジャガイモを傷つけないよう手で優しく掘り出す\n・直射日光を避けて風通しの良い日陰に広げ、半日ほど表面を乾燥させて保存性を高める",
    memo: "雨上がりの濡れた土で掘ると芋が腐る原因になるぞ！掘り出した芋に日光を当て続けると緑色に変色して毒素が出るから、すぐ日陰へ移動させよう。",
    reference_links: "https://example.com/agri/potato-harvest",
    source: "東京都『野菜栽培技術指針（バレイショ収穫）』",
    difficulty: 2,
    exp: 60,
    require_photo: false,
    badge_name: "大収穫ポテトキング",
    badge_icon: "🏆",
  },

  // ─── 根菜類：サトイモ ───
  {
    id: "tpl_taro_start",
    title: "🥔 【初回必須】サトイモの深溝植え付け＆初期潅水",
    target_crop: "サトイモ",
    category: "根菜",
    timing: "4月中旬〜下旬",
    estimated_time: "40分",
    tools_needed: "種芋, スコップ, 完熟堆肥, 化成肥料, ジョウロ",
    description:
      "【深溝掘削】クワとスコップで深さ15〜20cmの深い溝を掘る\n【元肥施用】溝の底に堆肥と化成肥料を薄くまき、底の土とよく混ぜて厚さ3cmほど土を戻す\n【種芋配置】芽の尖った方を上に向けて、株間45cmの間隔で種芋を一直線に並べる\n【厚め覆土・潅水】土を6〜8cmの厚さでしっかり被せて足で軽く踏み、ジョウロで水をたっぷり注ぎ込む",
    memo: "サトイモは東南アジア生まれで水が命！浅く植えると新しい芋が太らないから、深めの溝に植えて夏に向けて土をどんどん盛っていくよ。",
    reference_links: "https://example.com/agri/taro-start",
    source: "東京都『野菜栽培技術指針（サトイモ）』",
    difficulty: 2,
    exp: 45,
    require_photo: true,
    badge_name: "ウォーターラバー",
    badge_icon: "💧",
  },
  {
    id: "tpl_taro_care",
    title: "🌾 【乾燥防止】サトイモの追肥・土寄せ＆敷き藁マルチ",
    target_crop: "サトイモ",
    category: "根菜",
    timing: "6月下旬〜7月上旬",
    estimated_time: "45分",
    tools_needed: "クワ, 化成肥料, 敷き藁（または刈り草）, ジョウロ",
    description:
      "【追肥散布】本葉が3〜4枚展開した株の周りに、化成肥料20gを均一にまく\n【株元土寄せ】通路の土をクワでかき上げ、株元に高さ5cmほど厚く土を寄せる\n【敷き藁被覆】乾燥と地温上昇を防ぐため、株元の周囲に敷き藁を厚さ5cm以上でびっしり敷き詰める\n【徹底散水】敷き藁の上から水が染み渡るよう、ジョウロで時間をかけて徹底的に潅水する",
    memo: "多摩の真夏の猛暑はサトイモの大敵！敷き藁で土の水分を逃がさないようにガードすることが、ねっとり柔らかなサトイモに育てる秘訣だ。",
    reference_links: "https://example.com/agri/taro-care",
    source: "東京都『野菜栽培技術指針（サトイモ管理）』",
    difficulty: 2,
    exp: 50,
    require_photo: true,
    badge_name: "敷き藁シールド",
    badge_icon: "🛡️",
  },

  // ─── 根菜類：サツマイモ ───
  {
    id: "tpl_sweetpotato_start",
    title: "🍠 【初回必須】サツマイモの高畝成形＆船底挿し定植",
    target_crop: "サツマイモ",
    category: "根菜",
    timing: "5月下旬〜6月上旬",
    estimated_time: "45分",
    tools_needed: "苗（つる）, クワ, 黒マルチ, 移植ゴテ（または棒）, ジョウロ",
    description:
      "【高畝成形】水はけを良くするため、クワで幅30cm・高さ30cmのかまぼこ型の高畝を作る\n【マルチ被覆】畝に黒マルチを弛みなく張り、裾を土で埋めて株間35cmで穴を開ける\n【船底挿し】苗の先端の葉を地表に出し、地中に3〜4節が入るよう深さ5cm程度で水平気味（船底型）に挿す\n【密着鎮圧】挿したつるの周りの土を上から手のひらで強く押し固め、つると土を密着させて散水する",
    memo: "垂直に深く挿すとイモが巨大化して数が減る！水平気味の「船底挿し」にして地中の節の数を増やすと、形の良いイモが均一に実るよ。",
    reference_links: "https://example.com/agri/sweetpotato-start",
    source: "東京都『野菜栽培技術指針（カンショ）』",
    difficulty: 2,
    exp: 50,
    require_photo: true,
    badge_name: "船底ナビゲーター",
    badge_icon: "🚢",
  },
  {
    id: "tpl_sweetpotato_care",
    title: "🌿 【つるボケ防止】サツマイモのつる返し＆除草",
    target_crop: "サツマイモ",
    category: "根菜",
    timing: "7月下旬〜8月下旬",
    estimated_time: "30分",
    tools_needed: "軍手, 鎌",
    description:
      "・畝から通路へ旺盛に這い出たつるを手でしっかりと掴んで持ち上げる\n・つるの節から地面に向かって伸びた細い根（不定根）をバリバリと地面から引き剥がす\n・持ち上げたつるを通路からすべて畝の上へとひっくり返して載せる\n・つるの下に通路に生えている雑草を鎌で根元から刈り取る",
    memo: "つるの節から根が張ると、そこに無駄な小イモができて親玉が太らなくなる（つるボケ）！根を引き剥がして栄養を中心の芋へ集中させよう。",
    reference_links: "https://example.com/agri/sweetpotato-care",
    source: "東京都『野菜栽培技術指針（カンショ管理）』",
    difficulty: 1,
    exp: 35,
    require_photo: false,
    badge_name: "つる返しスイーパー",
    badge_icon: "🔄",
  },

  // ─── 根菜類：秋冬ダイコン ───
  {
    id: "tpl_radish_start",
    title: "⚪ 【初回必須】ダイコンの点まき・鎮圧＆不織布ベタがけ",
    target_crop: "秋冬ダイコン",
    category: "根菜",
    timing: "8月下旬〜9月上旬",
    estimated_time: "35分",
    tools_needed: "種子, 缶（底面平らなもの）, 不織布, U字ピン, ジョウロ",
    description:
      "【窪み作成】条間45cm・株間30cmで、缶の底を土に押し当てて深さ1.5cmの平らな窪みを作る\n【3粒点まき】窪みの中に重ならないよう等間隔で種を3粒落とし、土を1cm被せる\n【手のひら鎮圧】手のひらで体重をかけて土をギュッと強く押し固め、種と土を密着させる\n【ベタがけ密閉】害虫と乾燥を防ぐため畝全体に不織布を直接被せ、縁をピンで留めて上から散水する",
    memo: "ダイコンの根は敏感！小石や未熟堆肥に当たると「又根（二股）」になるぞ。播種する場所の真下はスコップで石を取り除いておこう。",
    reference_links: "https://example.com/agri/radish-start",
    source: "東京都『野菜栽培技術指針（ダイコン）』",
    difficulty: 1,
    exp: 40,
    require_photo: true,
    badge_name: "ダイコンアンカー",
    badge_icon: "⚪",
  },
  {
    id: "tpl_radish_care",
    title: "✂️ 【一本立ち】ダイコンの間引き・追肥＆青首土寄せ",
    target_crop: "秋冬ダイコン",
    category: "根菜",
    timing: "9月下旬〜10月上旬（本葉5〜6枚時）",
    estimated_time: "35分",
    tools_needed: "園芸ハサミ, 化成肥料, 移植ゴテ",
    description:
      "【間引き選抜】3本のうち最も葉が左右対称で美しく、茎が太い中心の1本を選び出す\n【根元切除】残す1本の根を絶対に揺らさないよう、間引く2本をハサミで根元から切り取る\n【株周り追肥】株から10cm離れた周りに化成肥料10gを環状にまき、土と軽く混ぜ合わせる\n【青首土寄せ】ダイコンがぐらつかないよう、地上に出ている白い首の根元へ土をしっかり寄せる",
    memo: "間引きが遅れるとダイコンが競合して細長くなってしまうぞ。間引いた葉は栄養満点の間引き菜として、浅漬けやお味噌汁で味わおう！",
    reference_links: "https://example.com/agri/radish-care",
    source: "東京都『野菜栽培技術指針（ダイコン管理）』",
    difficulty: 2,
    exp: 45,
    require_photo: true,
    badge_name: "センターピン選抜隊",
    badge_icon: "🎯",
  },

  // ─── 根菜類：秋ニンジン ───
  {
    id: "tpl_carrot_start",
    title: "🥕 【初回必須】ニンジンの浅溝筋まき＆遮光ネット保湿",
    target_crop: "秋ニンジン",
    category: "根菜",
    timing: "8月中旬〜下旬",
    estimated_time: "40分",
    tools_needed: "種子, 支柱（溝つけ用）, バーミキュライト, 遮光ネット, ジョウロ",
    description:
      "【浅溝つけ】条間20cmで支柱を土に軽く押し当て、深さ5mm〜1cmの極めて浅い播種溝を作る\n【すじまき】溝の中に種が重ならないよう約1cm間隔で筋状にタネを落としていく\n【極薄覆土鎮圧】バーミキュライトをタネが隠れる程度（厚さ3mm）に薄くかけ、手のひらで強く押し固める\n【遮光ネット被覆】発芽まで乾燥させないよう畝の上に遮光ネットを直に被せ、毎日欠かさず散水する",
    memo: "「ニンジンは芽が出れば半分成功」！光を好む好光性種子だから土は極薄くかけ、発芽するまでの1週間は絶対に乾かさないのが絶対ルールだ。",
    reference_links: "https://example.com/agri/carrot-start",
    source: "東京都『野菜栽培技術指針（ニンジン）』",
    difficulty: 3,
    exp: 60,
    require_photo: true,
    badge_name: "発芽の壁を越えし者",
    badge_icon: "🥕",
  },
  {
    id: "tpl_carrot_care",
    title: "✂️ 【美肌化】ニンジンの第2回間引き＆肩の土寄せ",
    target_crop: "秋ニンジン",
    category: "根菜",
    timing: "9月下旬〜10月上旬（本葉5〜6枚時）",
    estimated_time: "40分",
    tools_needed: "ピンセット（または指）, 三角ホー, 化成肥料",
    description:
      "・隣り合う株同士の間隔が10〜12cmになるよう、発育の遅い株を指先で真上に引き抜く\n・条間に1平方メートルあたり化成肥料20gを均一に散布する\n・三角ホーで表面の土を軽く耕しながら、ニンジンの根元の肩口へ土をしっかり寄せる\n・ニンジンの頭部が日光に当たって緑化するのを防ぐため、根の頭が土で完全に隠れた状態にする",
    memo: "ニンジンの頭が日光にさらされると緑色に変色してアクが強くなるぞ。間引きのタイミングでしっかり土を盛って肩を隠してあげよう。",
    reference_links: "https://example.com/agri/carrot-care",
    source: "東京都『野菜栽培技術指針（ニンジン管理）』",
    difficulty: 2,
    exp: 45,
    require_photo: false,
    badge_name: "キャロットブリーダー",
    badge_icon: "🧡",
  },

  // ─── 根菜類：コカブ ───
  {
    id: "tpl_turnip_start",
    title: "⚪ 【初回必須】コカブの筋まき＆サンサンネット完全トンネル",
    target_crop: "コカブ",
    category: "根菜",
    timing: "9月上旬〜下旬",
    estimated_time: "35分",
    tools_needed: "種子, サンサンネット（0.6〜0.8mm目）, ダンポール支柱, パッカー, ジョウロ",
    description:
      "【浅溝播種】条間20cmで深さ1cmの溝を引き、種を1cm間隔で筋まきして土を薄く被せて鎮圧する\n【トンネル骨組み】50cm間隔でアーチ支柱を畝をまたいで土中深く差し込む\n【防虫ネット展張】支柱の上にネットを被せ、弛みがないようパッカーで固定する\n【裾の土埋め】キスジノミハムシ等の侵入を防ぐため、ネットの裾全周にスコップで土を被せて密閉する",
    memo: "コカブの葉は虫の大好物！種をまいたらその場でネットをトンネル状に張り、裾を土で完全に埋めるのが真っ白で綺麗なカブを採る秘訣だ。",
    reference_links: "https://example.com/agri/turnip-start",
    source: "農林水産省『有機農業の栽培技術マニュアル（害虫防除）』",
    difficulty: 2,
    exp: 45,
    require_photo: true,
    badge_name: "スノーボール",
    badge_icon: "⚪",
  },

  // ─── 葉菜類：キャベツ ───
  {
    id: "tpl_cabbage_start",
    title: "🥬 【初回必須】キャベツ健苗定植＆防虫ネット完全密閉",
    target_crop: "キャベツ",
    category: "葉菜",
    timing: "9月上旬",
    estimated_time: "45分",
    tools_needed: "苗, 移植ゴテ, ダンポール支柱, サンサンネット（0.6〜0.8mm目）, パッカー, スコップ, ジョウロ",
    description:
      "【定植穴準備】株間40cmを測り、ポット同等の深さの植え穴を掘って水500mlを注ぎ、引くのを待つ\n【据付鎮圧】本葉5枚前後の健苗を根鉢を崩さず穴に入れ、周囲の土を寄せて株元を手のひらで軽く押さえる\n【トンネル設置】畝の上にアーチ支柱を差し、サンサンネットをピンと張りパッカーで固定する\n【全周裾埋め】アオムシ・コナガの侵入をゼロにするため、ネットの裾全周に土をスコップで被せて隙間なく埋める",
    memo: "秋のアオムシは恐ろしい食欲！定植当日にネットを張り、裾を土で埋め尽くすことがキャベツ栽培の成敗を100%決めるぞ。",
    reference_links: "https://example.com/agri/cabbage-start",
    source: "東京都『野菜栽培技術指針（キャベツ）』、農林水産省『有機農業マニュアル』",
    difficulty: 2,
    exp: 60,
    require_photo: true,
    badge_name: "トンネルディフェンダー",
    badge_icon: "🛡️",
  },
  {
    id: "tpl_cabbage_care",
    title: "🥬 【外葉拡大】キャベツ結球初期の追肥・除草中耕",
    target_crop: "キャベツ",
    category: "葉菜",
    timing: "10月上旬（定植後約20日、芯部が立ち上がり始めた頃）",
    estimated_time: "30分",
    tools_needed: "化成肥料, 三角ホー",
    description:
      "【ネット一時開放】ネットの片側の土をよけて持ち上げ、作業スペースを確保する\n【肩口追肥】株の周りの畝肩に、1平方メートルあたり化成肥料30gを均一にまく\n【中耕土寄せ】三角ホーで表面の土を軽く耕しながら肥料を混ぜ合わせ、株元へ土を寄せる\n【葉裏点検・再密閉】葉の裏に害虫がいないか目視点検した後、ネットを元に戻して裾に土を被せて再密閉する",
    memo: "キャベツが大きく丸くなるかは「外葉の大きさ」で決まる！結球が始まる前に追肥を効かせて、巨大な外葉を15枚以上育て上げよう。",
    reference_links: "https://example.com/agri/cabbage-care",
    source: "東京都『野菜栽培技術指針（キャベツ追肥）』",
    difficulty: 2,
    exp: 45,
    require_photo: true,
    badge_name: "ボールフォーマー",
    badge_icon: "🌪️",
  },

  // ─── 葉菜類：ブロッコリー ───
  {
    id: "tpl_broccoli_start",
    title: "🥦 【初回必須】ブロッコリーの定植＆防虫ネットガード",
    target_crop: "ブロッコリー",
    category: "葉菜",
    timing: "9月上旬",
    estimated_time: "45分",
    tools_needed: "苗, 移植ゴテ, 支柱, サンサンネット（0.6〜0.8mm目）, ジョウロ",
    description:
      "【株間確保】株間45cm・条間60cmで穴を掘り、底に水を注いで土を湿らせる\n【根鉢定植】本葉4〜5枚の苗を根鉢を崩さずに植え付け、深植えにならないよう地表と高さを合わせる\n【アーチ展張】トンネル支柱を設置し、上から防虫ネットを弛みなく被せて固定する\n【裾密閉潅水】ネットの裾を土に完全に埋め戻し、ネットの上からジョウロで十分に水を撒く",
    memo: "ブロッコリーの若い葉も虫の大好物！植え付けから初期成長まではネットの中で箱入り娘として育ててあげよう。",
    reference_links: "https://example.com/agri/broccoli-start",
    source: "東京都『野菜栽培技術指針（ブロッコリー）』",
    difficulty: 2,
    exp: 55,
    require_photo: true,
    badge_name: "ブロッコリーガード",
    badge_icon: "🥦",
  },
  {
    id: "tpl_broccoli_harvest",
    title: "🥦 【頂花蕾収穫】斜めカット＆側花蕾発生追肥",
    target_crop: "ブロッコリー",
    category: "葉菜",
    timing: "11月中旬〜翌1月",
    estimated_time: "25分",
    tools_needed: "収穫ハサミ, 化成肥料",
    description:
      "・中央の花蕾が直径12〜15cmに固く締まっていることを確認する\n・花蕾の直下5cmの位置の太い茎を、雨水が溜まらないよう斜めにハサミで切り落とす\n・切り口に水が溜まって腐敗するのを防ぐため、切り口の角度を45度に保つ\n・次の側花蕾の成長を促すため、株元に化成肥料15gをまいて土と軽く混ぜる",
    memo: "てっぺんの実（頂花蕾）を収穫した後も株を抜いちゃダメ！追肥しておけば、脇から一口サイズの側花蕾が春まで次々と採れるぞ。",
    reference_links: "https://example.com/agri/broccoli-harvest",
    source: "東京都『野菜栽培技術指針（ブロッコリー収穫）』",
    difficulty: 1,
    exp: 40,
    require_photo: true,
    badge_name: "クラウンハンター",
    badge_icon: "🥦",
  },

  // ─── 葉菜類：ハクサイ ───
  {
    id: "tpl_chinese_cabbage_start",
    title: "🥬 【初回必須】ハクサイ定植＆防虫トンネル密閉",
    target_crop: "ハクサイ",
    category: "葉菜",
    timing: "9月上旬",
    estimated_time: "45分",
    tools_needed: "苗, 移植ゴテ, 支柱, サンサンネット（0.6〜0.8mm目）, ジョウロ",
    description:
      "【定植穴準備】株間45cmを確保して穴を掘り、500mlの水を注ぎ込んで染み込ませる\n【定植】根鉢を崩さず苗を穴に入れ、土を被せて地表と水平になるよう軽く鎮圧する\n【防虫トンネル展張】アーチ支柱にネットを被せ、パッカーで固定する\n【裾の完全埋没】ネットの全周の縁にスコップで土を盛り上げ、隙間を完全に塞ぐ",
    memo: "ハクサイは結球の中心部を虫に食われると二度と丸くならない！初期のネット密閉が収穫できるかどうかの全てだ。",
    reference_links: "https://example.com/agri/chinese-cabbage-start",
    source: "東京都『野菜栽培技術指針（ハクサイ）』",
    difficulty: 2,
    exp: 55,
    require_photo: true,
    badge_name: "ハクサイキーパー",
    badge_icon: "🥬",
  },
  {
    id: "tpl_chinese_cabbage_tie",
    title: "🥋 【伝統の防寒】ハクサイの冬越し外葉結束",
    target_crop: "ハクサイ",
    category: "葉菜",
    timing: "12月中旬（強い霜が降りる前）",
    estimated_time: "30分",
    tools_needed: "稲わら（または麻紐）, 軍手",
    description:
      "・結球が固く締まったハクサイの前に立ち、広がっている外葉を手で包み込むように持ち上げる\n・外葉で中心の丸い結球部を完全に包み込み、ラグビーボールのような形にする\n・頭部から3分の1の位置を稲わらや麻紐でしっかりと縛り、風で開かないよう結ぶ\n・結束後、中心部に寒風や雪が直接当たらない状態になっていることを確認する",
    memo: "ハクサイ自身の外葉をマントのように巻いて寒風から守る伝統技！霜に当たることで糖度が増し、2月まで畑に置いたまま保存できるよ。",
    reference_links: "https://example.com/agri/chinese-cabbage-tie",
    source: "東京都『野菜栽培技術指針（ハクサイ越冬）』",
    difficulty: 2,
    exp: 45,
    require_photo: true,
    badge_name: "ハクサイ結束帯締め",
    badge_icon: "🥋",
  },

  // ─── 葉菜類：ホウレンソウ ───
  {
    id: "tpl_spinach_start",
    title: "🍃 【初回必須】石灰中和＆ホウレンソウ密着条まき",
    target_crop: "ホウレンソウ",
    category: "葉菜",
    timing: "9月下旬〜10月中旬",
    estimated_time: "40分",
    tools_needed: "苦土石灰, 種子, 支柱, 鎮圧板（木板等）, ジョウロ",
    description:
      "【酸度矯正】酸性を嫌うため、1平方メートルあたり苦土石灰150gをしっかり混ぜ込んでおく\n【播種溝作成】条間15cmで支柱を土に押し当て、深さ1cmの溝を作る\n【条まき】種皮が硬いため1〜2cm間隔で重ならないように均一に種をまき、土を1cm被せる\n【徹底鎮圧・潅水】木板を溝の上に置いて体重をかけてしっかり踏み固め、発芽するまで土を乾かさないよう散水する",
    memo: "ホウレンソウは酸性土壌が大嫌い！石灰でしっかり中和し、種と土を密着させて水を切らさないことが発芽の絶対条件だ。",
    reference_links: "https://example.com/agri/spinach-start",
    source: "東京都『野菜栽培技術指針（ホウレンソウ）』",
    difficulty: 2,
    exp: 45,
    require_photo: true,
    badge_name: "アルカリマスター",
    badge_icon: "🧪",
  },

  // ─── 葉菜類：コマツナ ───
  {
    id: "tpl_komatsuna_start",
    title: "🥬 【初回必須】コマツナの筋まき＆サンサンネットベタがけ",
    target_crop: "コマツナ",
    category: "葉菜",
    timing: "9月上旬〜10月上旬",
    estimated_time: "30分",
    tools_needed: "種子, 支柱, 不織布（または防虫ネット）, ジョウロ",
    description:
      "【浅溝作成】条間15cmで深さ5mm〜1cmの浅い溝を支柱で作る\n【筋まき覆土】種を1cm間隔ですじまきし、土を薄く被せて手のひらで軽く押さえる\n【ベタがけ被覆】害虫侵入と乾燥を防ぐため、資材を畝に直接ベタがけする\n【散水・発芽後撤去】ネットの上から散水し、芽が揃ったら徒長を防ぐため直ちにベタがけを外す",
    memo: "東京・多摩の誇る伝統葉菜！秋なら種まきから30日前後で収穫できる。発芽したらベタがけを外してしっかり日光に当てよう。",
    reference_links: "https://example.com/agri/komatsuna-start",
    source: "農林水産省『有機農業の栽培技術マニュアル（コマツナ）』",
    difficulty: 1,
    exp: 35,
    require_photo: true,
    badge_name: "スピードベジタブル",
    badge_icon: "⚡",
  },

  // ─── 葉菜類：長ネギ ───
  {
    id: "tpl_leek_start",
    title: "🥢 【初回必須】長ネギの30cm深溝掘り・苗直立並べ＆敷きわら",
    target_crop: "ネギ",
    category: "葉菜",
    timing: "6月中旬〜7月上旬",
    estimated_time: "50分",
    tools_needed: "苗, クワ, スコップ, 稲わら",
    description:
      "【深溝掘削】クワとスコップを使い、深さ30cm・幅15cmの垂直なV字溝を掘る\n【直立配置】溝の壁面（日陰側）に沿わせて、苗を5cm間隔でまっすぐ直立させて並べる\n【極薄覆土】苗の根元だけに厚さ2〜3cmの土を薄く被せ、倒れないよう手で軽く押さえる\n【敷きわら投入】根の通気性を確保し乾燥を防ぐため、溝の底に稲わらを厚さ5cmで敷き詰める",
    memo: "最初から深く埋めると息が詰まって腐ってしまう！最初は根元だけに薄く土をかけ、成長に合わせて土を埋め戻していくのが白い美肌ネギの秘密だ。",
    reference_links: "https://example.com/agri/leek-start",
    source: "東京都『野菜栽培技術指針（ネギ）』",
    difficulty: 3,
    exp: 65,
    require_photo: true,
    badge_name: "ホワイトシャフト",
    badge_icon: "🥢",
  },
  {
    id: "tpl_leek_care",
    title: "👔 【軟白化】長ネギの第2回追肥＆葉分岐下土寄せ",
    target_crop: "ネギ",
    category: "葉菜",
    timing: "9月上旬〜10月上旬",
    estimated_time: "40分",
    tools_needed: "クワ, 化成肥料",
    description:
      "・葉の分かれ目（首元）に向かって化成肥料を1平方メートルあたり30g均一にまく\n・クワを使って畝の土を溝へ崩し入れ、しっかりと厚く土を盛り上げる\n・ネギの成長点を埋めないよう、「葉の分かれ目の5cm下」までで土寄せを止める\n・盛り上げた土の表面をクワの背で軽く叩き、光が入らないよう固める",
    memo: "白い部分は土で日光を遮ることで作られる（軟白化）。分岐点より上まで埋めると成長が止まるから、必ず「分かれ目の下」をキープしよう！",
    reference_links: "https://example.com/agri/leek-care",
    source: "東京都『野菜栽培技術指針（ネギ管理）』",
    difficulty: 3,
    exp: 55,
    require_photo: true,
    badge_name: "ネギの襟立て師",
    badge_icon: "👔",
  },

  // ─── 葉菜類：タマネギ ───
  {
    id: "tpl_onion_start",
    title: "🧅 【初回必須】穴あきマルチ浅植え＆鎮圧",
    target_crop: "タマネギ",
    category: "葉菜",
    timing: "11月上旬〜中旬",
    estimated_time: "40分",
    tools_needed: "苗, 穴あきタマネギマルチ（条間15cm）, ジョウロ",
    description:
      "【苗の選定】太さが鉛筆よりやや細い（直径5〜7mm）の揃った苗を選び出す\n【浅穴あけ】マルチの穴に指を深さ2〜3cm押し込んで浅い植え穴を作る\n【浅植え】緑と白の境目が地表に出るよう浅く植え、周囲の土を寄せる\n【強鎮圧・潅水】冬の霜柱で浮き上がらないよう株元を指で強く押し固め、水をたっぷり撒く",
    memo: "太すぎる苗を植えると春にトウ立ち（芯が固くなる）し、細すぎると冬の寒さで枯れる。鉛筆より少し細い苗を選び、絶対に深く植えないこと！",
    reference_links: "https://example.com/agri/onion-start",
    source: "東京都『野菜栽培技術指針（タマネギ）』",
    difficulty: 3,
    exp: 50,
    require_photo: true,
    badge_name: "オニオンルーラー",
    badge_icon: "🧅",
  },
  {
    id: "tpl_onion_harvest",
    title: "🧅 【倒伏判定】タマネギの収穫・天日干し＆吊るし玉結束",
    target_crop: "タマネギ",
    category: "葉菜",
    timing: "5月下旬〜6月上旬",
    estimated_time: "45分",
    tools_needed: "収穫ハサミ, 麻紐, コンテナ",
    description:
      "・畑全体の7〜8割の茎が自然にバタバタと倒れたら収穫の合図とする\n・晴天の日に株元を持って垂直に引き抜き、畑の上に並べて半日天日干しする\n・根をハサミで切り落とし、葉を15cm残して上部を切り揃える\n・4〜5球ずつを麻紐でギュッと固結びし、雨の当たらない日陰の軒下に吊るす",
    memo: "葉が自然に倒れるのは熟したサイン！半日しっかりお日様に当てて首元を乾燥させてから吊るすと、冬まで腐らず長持ちするよ。",
    reference_links: "https://example.com/agri/onion-harvest",
    source: "東京都『野菜栽培技術指針（タマネギ収穫）』",
    difficulty: 1,
    exp: 40,
    require_photo: false,
    badge_name: "ゴールドオニオンハンガー",
    badge_icon: "🧅",
  },

  // ─── 伝統野菜：のらぼう菜（多摩特産・江戸東京野菜） ───
  {
    id: "tpl_norabona_start",
    title: "🏛️ 【初回必須】多摩伝統のらぼう菜の秋定植＆防虫ガード",
    target_crop: "のらぼう菜",
    category: "葉菜",
    timing: "10月中旬〜11月上旬",
    estimated_time: "35分",
    tools_needed: "苗, 移植ゴテ, 不織布トンネル, ジョウロ",
    description:
      "【株間配置】春に巨大化するため株間45cm・条間50cmの広い間隔をとって穴を掘る\n【定植鎮圧】本葉4〜5枚の苗を根鉢を崩さずに据え置き、土を寄せて手のひらで軽く押さえる\n【トンネル被覆】冬の寒風と霜から守るため、畝全体に不織布トンネルを設置する\n【潅水】トンネルの裾を固定し、ジョウロで畝全体にたっぷり散水する",
    memo: "西多摩地方で江戸時代から受け継がれてきた伝統野菜！強健で寒さに極めて強く、多摩の冬を越えて春に最高の甘みをもたらしてくれるよ。",
    reference_links: "https://example.com/agri/norabona-start",
    source: "東京都産業労働局『江戸東京野菜（のらぼう菜栽培マニュアル）』",
    difficulty: 2,
    exp: 50,
    require_photo: true,
    badge_name: "伝統の継承者",
    badge_icon: "🏛️",
  },
  {
    id: "tpl_norabona_harvest",
    title: "🌿 【ポキポキ収穫】のらぼう菜の主茎摘心＆春のわき芽収穫",
    target_crop: "のらぼう菜",
    category: "葉菜",
    timing: "3月上旬〜4月下旬",
    estimated_time: "30分",
    tools_needed: "収穫袋, 化成肥料",
    description:
      "・伸びてきた主茎（トウ）の先端に花芽がついたら、先端から15cmの位置を手でポキッと折って摘心する\n・側枝の発生を促すため、株元に化成肥料20gを追肥して軽く土と混ぜる\n・次々と伸びてくる側枝のトウを手で折れる柔らかい位置でポキポキと収穫する\n・花が開いて黄色くなるとスジ張るので、つぼみのうちに収穫を続ける",
    memo: "ハサミを使わずに「手でポキッと自然に折れる位置」で収穫するのが極意！そこが一番スジがなくて柔らかく、生でも甘い絶品部分だよ。",
    reference_links: "https://example.com/agri/norabona-harvest",
    source: "東京都産業労働局『江戸東京野菜（のらぼう菜収穫）』",
    difficulty: 1,
    exp: 45,
    require_photo: true,
    badge_name: "のらぼうマスター",
    badge_icon: "🌿",
  },
];
